const KBYTE = 1024
const MBYTE = 1024 * KBYTE

export const MAX_INPUT_SIZE = 100 * MBYTE
export const MAX_OUTPUT_SIZE = 10 * MBYTE
export const MAX_QUEUE_BUFFER_SIZE = 10 * KBYTE

const SECOND = 1000
export const MAX_BUSBOY_FINISH_TIME = 120 * SECOND
